theme: jekyll-theme-cayman
title: Eugenio Chaves
show_downloads: true
google_analytics: G-4NF1EXTE9X
github:
  zip_url: https://eugenio-chaves.github.io/
  home: https://www.linkedin.com/in/eugenio-betine/